"""SHANn

Revision ID: 287a3cf31b84
Revises: 3328ff109aa7
Create Date: 2022-04-04 12:26:15.416620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287a3cf31b84'
down_revision = '3328ff109aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'addr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('addr', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
